### ISSUE TITLE
Undefined in POSIX warning from shellcheck.net

### ISSUE THREAD

**Issue by brother** [apiraino/autorandr#1]
Nice hack. The only warning for [autorandr.sh](https://github.com/apiraino/autorandr/blob/master/autorandr.sh) at shellcheck.net was for [line 9](https://github.com/apiraino/autorandr/blob/master/autorandr.sh#L9) where you do a illegal redirect.

Depending on what outcome you expect you should change this, for instance to 2>&1. Look at Redirections at [wooledge](http://mywiki.wooledge.org/Bashism) for instance.

**Comment by apiraino** [comment]
Hello @brother and thank you for pointing me to that validator, I didn't know of such tool. It will come particularly handy now that I'm working on another shell thingie.
